name: NimbusEvents
version: ${project.version}
author: evankunmc
description: An events management plugin for NimbusRealms
main: com.evankunmc.nimbusEvents.NimbusEvents
api-version: '1.21'
softdepend:
  - Citizens

commands:
  events:
    description: User-level command, enables users to join and leave active events
    permission: nimbusevents.event
    usage: "Usage: /events [join|leave] [event name]"
  nimbusevents:
    description: Admin-level command, enables admins to verify plugin data
    permission: nimbusevents.admin
    usage: "Usage: /nimbusevents [info|list|start|end|ip] [args]"

permissions:
  nimbusevents.event:
    description: User-level permission of NimbusEvents
    default: true
  nimbusevents.bypassalt:
    description: This permission bypasses the alt checker
    default: false
  nimbusevents.admin:
    description: Admin-level permission of NimbusEvents
    default: op